### ISSUE TITLE
investigate using flutter-rs plugins with "regular" flutter

### ISSUE THREAD

**Issue by dvc94ch** [flutter-rs/flutter-rs#119]

**Comment by rodydavis** [comment]
With dart ffi right? 😉

**Comment by dvc94ch** [comment]
do you have an idea of how this would work? I've not looked into it yet, but it seems like this would be a good as the custom embedding using winit/glutin will be buggy for a while, due to a shortage of non linux devs working on these projects.

**Comment by rodydavis** [comment]
![twitter_71a4027bec014e56368ae1deeee51f1f](https://user-images.githubusercontent.com/31253215/75703375-35611680-5c6c-11ea-9324-f63e0c4bd92c.jpeg)

This is my current plan. I am making good progress too. 

Im running my experiments here: https://github.com/rodydavis/flutter_ffi_webassembly/tree/master/rusty_ffi_flutter

The basic concept is to compile the rust code to WebAssembly and have a wrapper that uses WASI for Mobile and Desktop and directly calls web assembly on web. 

I could and probably am completely wrong, but i am just trying to see how far i can go with it.

**Comment by dvc94ch** [comment]
So is this a completely different setup to flutter-rs? Or is there some kind of intersection?

**Comment by rodydavis** [comment]
Possibly an intersection. I have a simple prototype working across mobile, web and desktop using wasm output from a rust lib. I report back more soon

**Comment by csnewman** [comment]
I think this goes quite outside the scope of this project. Most flutter-rs plugins will depend on internals from our implementation and therefore will not be easily translated.

Closing for now. We can look back into this once flutter for desktop has stabilised
