### ISSUE TITLE
flutter + rs on (macos) desktop

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [flutter-rs/flutter-rs#133]
I've been investigating flutter for the desktop for a new project.
I develop on Mac, but want to develop for cross-platform.

I was happy to see and be able to use the flutter desktop support as documented here: https://flutter.dev/desktop 

But I haven't figured out how to do flutter development in rust using flutter-rs for the desktop. 

I think the problems are related to the use of a specific flutter-engine?

Sorry it's a bit of a vague question - but, is it possible for me to configure things to use flutter-rs, compatible with flutter master channel to get support for desktop on macos?

**Comment by dvc94ch** [comment]
Why do you need the master channel? We support stable, beta and dev.

**Comment by dvc94ch** [comment]
If you really want to use the master channel find the engine version of the dev channel and export FLUTTER_ENGINE_VERSION

**Comment by stuartmorgan** [comment]
> I was happy to see and be able to use the flutter desktop support as documented here: https://flutter.dev/desktop
> [...]
> is it possible for me to configure things to use flutter-rs, compatible with flutter master channel to get support for desktop on macos?

If you're using flutter-rs, you won't be using anything described on that page. flutter-rs is a completely separate implementation from the official Flutter desktop support, with separate tooling, plugins, etc.; it's something you would use instead of what's on that page, not with it.

**Comment by andrewdavidmackenzie** [comment]
It states that for desktop support of flutter you should use master channel.

**Comment by andrewdavidmackenzie** [comment]
OK. I need to get my head around that.

I can’t get the sample or demo apps to run - and am not sure if it’s some
interaction with the standard flutter that I need to fix, or just a
flutter-rs issue.

I’ll maybe start with a clean flutter-rs install on Linux (with no other
flutter installed) and go step by step....

**Comment by andrewdavidmackenzie** [comment]
I tried on my linux box.

- rust was installed already
- downloaded and configured flutter sdk
- cloned flutter-app-demo
- cd into flutter-app-demo directory
- ran cargo flutter run

> error: failed to run custom build command for `flutter-engine-sys v0.4.0 (https://github.com/flutter-rs/flutter-rs#395ccbec)`
> 
> Caused by:
>   process didn't exit successfully: `/home/andrew/workspace/flutter-app-demo/target/flutter/debug/build/flutter-engine-sys-fed6e280250d3f04/build-script-build` (exit code: 101)
> --- stdout
> cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
> cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
> 
> --- stderr
> thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1188:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by dvc94ch** [comment]
Bindgen requires clang. `sudo apt-get install libclang-dev`

**Comment by dvc94ch** [comment]
Maybe the README should contain the words alpha or beta.

Anyway the error message is very clear on what the issue is. An error message is not a bug, in this case it's telling you what is wrong and politely asking you to fix it.

**Comment by dvc94ch** [comment]
@andrewdavidmackenzie I'm on the flutter-rs gitter, incase you require further assistance.
