### ISSUE TITLE
Window flushes black when resizing

### ISSUE THREAD

**Issue by btwael** [flutter-rs/flutter-rs#14]
I don't know if this is an issue on other platform or not, but in macOS, when you resize the window, it flush black then it render! so it's like there is no mechanism that resize the flutter content dynamically so it feel more natural.

If you take a look to [feather-apps](https://feather-apps.com), their application flush black less when resizing.

That's the behavior, we suppose to get

![](https://cdn-images-1.medium.com/max/800/1*Z7gmjdcuw9O26mM9Zaqnmg.gif)

**Comment by gliheng** [comment]
I know this problem exist, but haven't found a solution yet. The google desktop embedding also suffer from this problem. That made me think it's a flutter engine issue. But if feather apps works fine, there must be a workaround.

**Comment by btwael** [comment]
So, I was trying to fix this one last month, but the safety of rust and my lack of deep understanding of how plugin are implemented stopped me! but here is my idea:

The drawing context should be big enough with fixed size, so instead of resizing it and communicating the resize to flutter, we keep it in big enough size and communicate the resizing event information to the application via a plugin, and the application should draw itself only in the visible area.

I don't know if you get my idea, like my english is bad, but I can clarify.

**Comment by gliheng** [comment]
That could work, but how big should this context be? Also I need to figure out how to set this context size. It seems glfw handles this context size. When you resize window, you get framebuffer size from glfw's callback.

**Comment by btwael** [comment]
When the window is created, we create a big enough window (eg. screen size) and communicate that to flutter, when resizing we should not call `FlutterEngineSendWindowMetricsEvent` but instead communicate the new size via a plugin to the main widget.

The context size changes but flutter shouldn't be aware of it.

**Comment by gliheng** [comment]
This issue will probably related to this issue in flutter-engine https://github.com/flutter/flutter/issues/30671

**Comment by gliheng** [comment]
This issue will probably related to this issue in flutter-engine https://github.com/flutter/flutter/issues/30671

**Comment by csnewman** [comment]
Issue fixed upstream.
