### ISSUE TITLE
Is it possible to run without X?

### ISSUE THREAD

**Issue by geofmureithi** [flutter-rs/flutter-rs#141]
*Question:*
How would one need to approach to run this without X?
Similar to https://github.com/ardera/flutter-pi

**Comment by csnewman** [comment]
`futter-rs` does not provide an pre-made solution for running without X/Wayland.

There are 2 main options
- Use a kiosk display manager, such as [cage](https://github.com/Hjdskes/cage) with `flutter-winit`. This will be the most feature complete.
- Create a custom embedder. We expose `flutter-engine` as a high level wrapper around the flutter engine, which then only leaves the task of initialising OpenGL. I am currently working on such an embedder [flutter-drm](
https://github.com/csnewman/flutter-drm) however that is not yet production ready.
