### ISSUE TITLE
build and link `libflutter_engine` statically

### ISSUE THREAD

**Issue by shekohex** [flutter-rs/flutter-rs#59]
Hello, Is there is any reason why we don't already build the flutter-engine and link it as a static library? it would make it easier to bundle the whole application and send it to the consumer.

Also, I made a try to build my simple (counter) project to ` musl` target. but it failed to compile `glfw`, anyway it's not related maybe I would open another issue for that.

Here is some information about my system:
```
$ uname -a
Linux Hex 4.19.60-1-MANJARO #1 SMP PREEMPT Sun Jul 21 12:17:26 UTC 2019 x86_64 GNU/Linux

$ rustc -Vv                
rustc 1.38.0-nightly (dddb7fca0 2019-07-30)
binary: rustc
commit-hash: dddb7fca09dc817ba275602b950bb81a9032fb6d
commit-date: 2019-07-30
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 9.0
```

**Comment by gliheng** [comment]
Hi, shekohex. flutter-engine prebuilt dynamic library is currently downloaded from google, and they're not providing a static library. Building flutter-engine is a complex procedure, so is not mixed into this project. We currently have python scripts to build distribution formats snap (linux) windows(NSIS), mac (app). You can use that for the time being.

**Comment by shekohex** [comment]
Ok, great, so i was wondering why the resulted bundle is huge, currently the libflutter_engine around ~23MB stripped.
I know I'm asking for something that we can't control right now, but how, is there anything different than that one is built for Android for example?
The simple hello world flutter app on Android around ~5MB in the release mode 
So why there is a huge difference?
Is the download script downloads the debug build?

**Comment by shekohex** [comment]
Also I will be happy to provide a way to build the flutter engine locally as an option instead of download.
Maybe we could introduce a `static-bundled` feature flag, which is disabled by default, if enabled then we download and build it statically.
Is that ok ?

**Comment by gliheng** [comment]
Yes, the binary is indead debug build, and is download according to this wiki  https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders
I'd like to explore ways to incorporate AOT release engine into this project. But at the moment, you need to compile flutter engine yourself.

**Comment by gliheng** [comment]
If you have a good solution any time soon, welcome to open a PR. : )

**Comment by ytain** [comment]
As of today, by using the flutter channel master, you can compile the desktop example for mac, and the resulting binary size is 39MB, and while I compiled your rust flutter app demo, it comes to about  71MB which is almost double.

I inspected the flutter-desktop-embedding example produced binary for macos, it doesn't contain anymore any of the snapshots that you would get while compiling with rust way, and the compiled dart project for macos example is fully embedded inside the App.framework binary along with the aot artifacts.

Perhaps it's a good idea to see what the new changes to the flutter master channel were introduced that could be brought to the rust version of the project?

**Comment by ytain** [comment]
Also the correct instructions to compile the flutter example for desktop in flutter-desktop-embedding is following:

#you have flutter channel set to master 'flutter channel master && flutter upgrade'
#in the flutter-desktop-embedding github project
cd ./example
export ENABLE_FLUTTER_DESKTOP=true
flutter precache --macos
flutter packages get
flutter build macos --release #you can also add the option -v for verbose output
cd ./build/macos/build/Products/Release
#here you can find the built app

**Comment by BrandonDyer64** [comment]
In an ideal world, someone that has Rust and its required dependencies will already have everything they need to build and run an application built with `flutter-rs`.

Even if Python is required, libglfw3 and the Flutter SDK should not need to be installed separately, and should not require developer intervention.

After cloning a project that uses flutter-rs, assuming I have Python, rustc, cargo, and a C/C++ compiler installed, one should only need to run `cargo run` to see results.

**Comment by gliheng** [comment]
@BrandonDyer64  I agree that build tool should take care of libglfw3 and some recursive dependencies. On that, more work is needed, flutter SDK however is huge and complex. Probably better if developer takes care of their own. People use this library since they are also flutter developers.

**Comment by dvc94ch** [comment]
`flutter-engine` doesn't support static builds. Feel free to reopen once it does https://github.com/flutter/flutter/issues/33835
