### ISSUE TITLE
Publish flutter-plugins crate

### ISSUE THREAD

**Issue by Sach97** [flutter-rs/flutter-rs#68]
Hi @gliheng thank's for this amazing project. I was wondering why flutter-plugins was'nt published on crates.io yet is there a particular reason ? I noticed this when trying to run the example with version numbers vs the relative path in cargo.toml. Also I managed to solve some OpenGL issues on ubuntu so if you want me document this somewhere let me know I'd be glad to make a PR.

**Comment by gliheng** [comment]
Oh, sorry my bad. Forgot to publish this plugins crate. Thanks for the tip. Also what exactly is this OpenGL issue you talked about? It'd be nice if you can submit a PR. If you  want a place to put documentation. Feel free to make a docs folder and put markdown inside.

**Comment by gliheng** [comment]
https://crates.io/crates/flutter-plugins   There you go. Documentation is still WIP :).

**Comment by Sach97** [comment]
Thank's ! 
The error I had was `/usr/bin/ld: cannot find -lGL` he turns out opengl was'nt installed. I followed those [instructions](https://github.com/intel/compute-runtime/releases) and added a symilink `sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/libGL.so` to install opengl and it worked fine.

**Comment by gliheng** [comment]
I think I had the same problem. Solved it by `apt-get install libgl-dev` or something. I might need to add this deps to the doc.
