### ISSUE TITLE
wireguard - https://github.com/cloudflare/boringtun

### ISSUE THREAD

**Issue by joeblew99** [flutter-rs/flutter-rs#84]
I am thinking about integrating the wireguard ( boringtun) with flutter.
Not sure though is flutter-rs is at a stage where it could that.
The FFI bindings should allow to build a wireguard GUI in flutter and then talk directly over FFI to configure it - in theory.
And then all the flutter network calls would be using wireguard.

Pretty cool if it works.

**Comment by gliheng** [comment]
I think this should work. The configuration interface wouldn't be too complex to build. Also, platform compatibility is taken care of by flutter and rust. Are you going to build such a GUI client? Let me know if you encountered any issues when doing this.

**Comment by winwisely99** [comment]
We started the basis of it here: https://github.com/winwisely99/main/issues/63

**Comment by dvc94ch** [comment]
I'm not sure what a vpn tunnel has to do with `flutter-rs`. Can you elaborate what is required from `flutter-rs`?

**Comment by dvc94ch** [comment]
Closing as out-of-scope.

**Comment by csongorkeller** [comment]
Hi there,
did you maybe have something working with boringTun and flutter-rs? I'm in the same situation when would like to use boringtun with flutter-rs. Is it working btw together?
