### ISSUE TITLE
replace glfw with winit

### ISSUE THREAD

**Issue by dvc94ch** [flutter-rs/flutter-rs#87]
I think this would be a first step towards android/ios support, since winit already supports those platforms.

**Comment by gliheng** [comment]
I'll look into it. Thanks for your suggestion

**Comment by dvc94ch** [comment]
I took a stab at doing it myself. I'm having the issue that present is never called, if I replace `clear_current` with `present` it shows a FAB. Do any of the plugins need to be working for `present` to be called?

**Comment by dvc94ch** [comment]
So the winit port works on wayland and x11. Getting it to work on android is going to be a chunk more work, the winit android backend is currently unmaintained and needs some attention.

**Comment by dvc94ch** [comment]
Only thing missing is copying the assets from the apk to the fs before starting flutter. Will be opening pr's next week

**Comment by gliheng** [comment]
Wow. Can't wait to try this on android. I have less experience on IOS. I wonder how much more work is needed to have this working on IOS?

**Comment by dvc94ch** [comment]
winit/glutin currently have support for ios, but I haven't tried it. The flutter engine would need to be cross compiled with the embedder api enabled and there is a cargo plugin called `cargo-lipo` that would take care of building an ios app. Ideally very little code would be needed, just some platform specific loading of assets, but I've never used ios so I don't know.
