### ISSUE TITLE
Separate codec etc from glfw

### ISSUE THREAD

**Issue by csnewman** [flutter-rs/flutter-rs#88]
In my current project I have had to duplicate the codec, channel and plugin code from this project as I am not using GLFW (I'm using drm/kms). It would be nice if the project could be broken down into more reusable packages, something such as

flutter-engine-sys: the ffi code
flutter-engine-codec: codec
flutter-engine-channels: channel code
flutter-engine-plugins: text-input etc, each plugin could be a feature flag
flutter-engine-glfw: current logic around glfw rendering
flutter-engine-winit: #87 for example.

This would then allow me to reuse the codec logic, and push any bug fixes etc upstream without having to maintain a only slightly changed fork.

**Comment by csnewman** [comment]
I have opened #89 as a starting point. I will follow up with more PRs after this once has been merged.

**Comment by csnewman** [comment]
After some more thought, I think having so many packages probably isn't worthwhile/possible. I instead propose:

flutter-engine-sys: the ffi code
flutter-engine: codec, channels, pointer events, tasks etc (i.e. wrapper around sys crate)
flutter-engine-plugins: text-input etc, each plugin could be a feature flag
flutter-engine-glfw: current logic around glfw rendering
flutter-engine-winit: #87 for example

This would then allow me to reuse all the logic around tasks and channels, i.e. everything to do with the flutter engine without the rendering logic and window handling.

**Comment by gliheng** [comment]
Hi, csnewman. I agree that five crates look good at the current state. Thanks for you PR.
