### ISSUE TITLE
GL error

### ISSUE THREAD

**Issue by mmacedoeu** [flutter-rs/flutter-rs#9]
Got the error from https://github.com/flutter/flutter/issues/11094
And could not enable soft rendering like at https://github.com/flutter/flutter/issues/11094#issuecomment-373530604 because this option is not available with FlutterEngineArgs

**Comment by gliheng** [comment]
Hi, I added an option in FlutterEngineArgs. Now you can set command_line_args manually, instead of using default ones. https://github.com/gliheng/flutter-rs/commit/98445ccb81baba66fd42f1e770ee148743f2fd92  Since I cannot reproduce the error. Can you check if that is working?

**Comment by dvc94ch** [comment]
@mmacedoeu feel free to reopen the issue if it's not fixed
